import{a as S,S as B,i as l}from"./assets/vendor-73qhTu8_.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const q="55677845-05ff8047ada01a07b33efb575",F="https://pixabay.com/api/";async function f(t,o=1){const s={key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15};return(await S.get(F,{params:s})).data}const g=document.querySelector(".gallery"),m=document.querySelector(".loader"),c=document.querySelector(".load-more-btn"),M=new B(".gallery a",{captionsData:"alt",captionDelay:250});function p(t){const o=t.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:n,comments:w,downloads:P})=>`
                <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${s}" alt="${e}" />
      </a>
      <div class="info">
        <div class="info-item"><b>Likes</b><span>${r}</span></div>
        <div class="info-item"><b>Views</b><span>${n}</span></div>
        <div class="info-item"><b>Comments</b><span>${w}</span></div>
        <div class="info-item"><b>Downloads</b><span>${P}</span></div>
      </div>
    </li>`).join("");g.insertAdjacentHTML("beforeend",o),M.refresh()}function $(){g.innerHTML=""}function h(){m.classList.add("is-visible")}function y(){m.classList.remove("is-visible")}function b(){c&&c.classList.add("is-visible")}function v(){c&&c.classList.remove("is-visible")}const C=document.querySelector(".form"),u=document.querySelector(".load-more-btn");let d="",i=1;const L=15;C.addEventListener("submit",R);u&&u.addEventListener("click",E);async function R(t){t.preventDefault();const o=t.currentTarget.elements["search-text"].value.trim();if(!o){l.warning({message:"Please enter a search query!",position:"topRight"});return}d=o,i=1,$(),v(),h();try{const s=await f(d,i);if(s.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFF",iconColor:"#FFF",progressBarColor:"#B51B1B"});return}p(s.hits);const a=Math.ceil(s.totalHits/L);i<a&&b()}catch(s){console.log(s),l.error({message:"Something went wrong. Please try again later!",position:"topRight"})}finally{y(),t.target.reset()}}async function E(){i+=1,v(),h();try{const t=await f(d,i);p(t.hits),O();const o=Math.ceil(t.totalHits/L);i>=o?l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):b()}catch(t){console.log(t),l.error({message:"Failed to load more images. Please try again!",position:"topRight"})}finally{y()}}function O(){const t=document.querySelector(".gallery-item");if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
