import{a as m,S as d,i as n}from"./assets/vendor-bEqFC_vW.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const f="55677845-05ff8047ada01a07b33efb575",g="https://pixabay.com/api/";function y(s){const o=new URLSearchParams({key:f,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"});return m.get(`${g}?${o}`).then(r=>r.data).catch(r=>{throw console.error("Sorry, there are no images matching your search query. Please, try again!",r),r})}const p=document.querySelector(".gallery"),l=document.querySelector(".loader"),h=new d(".gallery a",{captionsData:"alt",captionDelay:250});function b(s){const o=s.map(({webformatURL:r,largeImageURL:i,tags:e,likes:t,views:a,comments:c,downloads:u})=>`
                <li class="gallery-item">
      <a class="gallery-link" href="${i}">
        <img class="gallery-image" src="${r}" alt="${e}" />
      </a>
      <div class="info">
        <div class="info-item"><b>Likes</b><span>${t}</span></div>
        <div class="info-item"><b>Views</b><span>${a}</span></div>
        <div class="info-item"><b>Comments</b><span>${c}</span></div>
        <div class="info-item"><b>Downloads</b><span>${u}</span></div>
      </div>
    </li>`).join("");document.querySelector(".gallery").innerHTML=o,h.refresh()}function v(){p.innerHTML=""}function L(){l.classList.add("is-visible")}function S(){l.classList.remove("is-visible")}const q=document.querySelector(".form");document.querySelector(".gallery");document.querySelector(".loader");q.addEventListener("submit",P);function P(s){s.preventDefault();const o=s.currentTarget.elements["search-text"].value.trim();if(!o){n.warning({message:"Please enter a search query!",position:"topRight"});return}v(),L(),y(o).then(r=>{if(r.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFF",iconColor:"#FFF",progressBarColor:"#B51B1B"});return}b(r.hits)}).catch(r=>{console.log(r),n.error({message:"Something went wrong. Please try again later!",position:"topRight"})}).finally(()=>{S(),s.target.reset()})}
//# sourceMappingURL=index.js.map
