import{a as B,S as q,i}from"./assets/vendor-73qhTu8_.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const M="55677845-05ff8047ada01a07b33efb575",F="https://pixabay.com/api/";async function g(t,o=1){const s={key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15};return(await B.get(F,{params:s})).data}const d=document.querySelector(".gallery"),m=document.querySelector(".loader"),c=document.querySelector(".load-more-btn"),R=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(t,o=!1){const s=t.map(({webformatURL:a,largeImageURL:e,tags:r,likes:l,views:w,comments:P,downloads:S})=>`
                <li class="gallery-item">
      <a class="gallery-link" href="${e}">
        <img class="gallery-image" src="${a}" alt="${r}" />
      </a>
      <div class="info">
        <div class="info-item"><b>Likes</b><span>${l}</span></div>
        <div class="info-item"><b>Views</b><span>${w}</span></div>
        <div class="info-item"><b>Comments</b><span>${P}</span></div>
        <div class="info-item"><b>Downloads</b><span>${S}</span></div>
      </div>
    </li>`).join("");o?d.insertAdjacentHTML("beforeend",s):d.innerHTML=s,R.refresh()}function $(){d.innerHTML=""}function p(){m.classList.add("is-visible")}function y(){m.classList.remove("is-visible")}function b(){c&&c.classList.add("is-visible")}function v(){c&&c.classList.remove("is-visible")}const C=document.querySelector(".form"),f=document.querySelector(".load-more-btn");let u="",n=1;const L=15;C.addEventListener("submit",E);f&&f.addEventListener("click",H);async function E(t){t.preventDefault();const o=t.currentTarget.elements["search-text"].value.trim();if(!o){i.warning({message:"Please enter a search query!",position:"topRight"});return}u=o,n=1,$(),v(),p();try{const s=await g(u,n);if(s.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFF",iconColor:"#FFF",progressBarColor:"#B51B1B"});return}h(s.hits);const a=Math.ceil(s.totalHits/L);n>=a?i.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):b()}catch(s){console.log(s),i.error({message:"Something went wrong. Please try again later!",position:"topRight"})}finally{y(),t.target.reset()}}async function H(){n+=1,v(),p();try{const t=await g(u,n);h(t.hits),O();const o=Math.ceil(t.totalHits/L);n>=o?i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):b()}catch(t){console.log(t),i.error({message:"Failed to load more images. Please try again!",position:"topRight"})}finally{y()}}function O(){const t=document.querySelector(".gallery-item");if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
